python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/3tui_ADP_C_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1p9b_GDP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1g9v_HEM_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/2po0_ADP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1h74_ADP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/2zfb_HEM_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1ls9_HEM_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/3jv2_ADP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1u0x_HEM_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/4g5r_GDP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1sd0_ADP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/3cy0_HEM_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/4arz_GDP_B_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1b38_ATP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1ek0_GDP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1f2u_ATP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/3e1y_ATP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/3lev_ATP_H_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/3tui_ADP_C_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1p9b_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1g9v_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/2po0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1h74_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/2zfb_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1ls9_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/3jv2_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1u0x_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/4g5r_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1sd0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/3cy0_HEM_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/4arz_GDP_B_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1b38_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1ek0_GDP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1f2u_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/3e1y_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/3lev_ATP_H_1.pdb
python pdb_launcher.py -s ./poc_sample/1e79_ATP_A_1.pdb -t ./poc_sample/1e79_ATP_A_1.pdb
