python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6r_GDP_1_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_SAM_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6v_FMN_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_AMU_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lin_E13_B_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lj0_ADP_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3liw_RUP_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lio_TRE_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6x_ATP_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg9_GLN_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lit_E15_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/1sg0_STL_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6t_ATP_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9mht_SAH_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6s_BCN_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lir_EEC_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/3lil_EEA_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/2r6n_CKE_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9ldb_NAD_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/2r6r_GDP_1_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/1sg9_SAM_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/2r6v_FMN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/9lyz_AMU_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3lin_E13_B_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3lj0_ADP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3liw_RUP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3lio_TRE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/2r6x_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/1sg9_GLN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3lit_E15_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/1sg0_STL_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/2r6t_ATP_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/9mht_SAH_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/2r6s_BCN_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3lir_EEC_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/3lil_EEA_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/2r6n_CKE_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/9ldb_NAD_A_1.pdb
python pdb_launcher.py -s ./poc_sample2/9lyz_NAG_A_1.pdb -t ./poc_sample2/9lyz_NAG_A_1.pdb
